version: '3.9'

services:
  postgres_duckcloud:
    image: postgres:15.0
    environment:
      POSTGRES_DB: duckcloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    networks:
      - duckcloud-network
    volumes:
      - duckcloud_postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2023-01-20T02-05-44Z.fips
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin@secret
    command: server --console-address ":9001" /data
    networks:
      - duckcloud-network

networks:
  duckcloud-network:
    driver: bridge

volumes:
  duckcloud_postgres_data:
    external: false