spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/duckcloud
    username: postgres
    password: postgres

  ## Keycloak SSO Authentication Server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/market
      client:
        provider:
          market:
            token-uri: http://localhost:8080/realms/market/protocol/openid-connect/token
        registration:
          market:
            authorization-grant-type: client_credentials
            client-id: duckcloud-webservice
            client-secret: mqZqOOLh9pUEXNclDI7k9Lz1AymXptWE

app:
  client:
    registration:
      name: market
      keycloak-admin-uri: http://localhost:8080/admin/realms/market
  auth:
    allowed-origins: http://localhost:4200
  storage:
    endpoint: http://127.0.0.1:9000
    accessKey: SykAM0TXTf3OVp5j
    secretKey: JI4xH7DoE3q4GWlpomjiq3l6lkTn2xVS
  onlyoffice:
    jwt:
      secret: WlEJf7hdzCEGwTWkO89i
  server:
    public-base-url: "http://trodix.local:8010"

sentry:
  dsn: "http://28cd491830984272b4d33684a9d53ce1@localhost:9010/2"
  traces-sample-rate: 1.0