server:
  port: 8010

spring:
  profiles:
    active: dev
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

mybatis:
  config-location: classpath:db/mybatis/mybatis-config.xml
  mapper-locations: classpath:db/mybatis/*-mapper.xml
  type-aliases-package: com.trodix.duckcloud.persistance.entities

### Allow Spring Boot Admin to display logs on /admin/instances/<INSTANCE>/logfile
# Must be same path as in logback-spring.xml
logging:
  file:
    name: logs/application.log

# swagger-ui custom path
springdoc:
  swagger-ui.path: /swagger-ui.html
  show-actuator: true

## Elasticsearch
app:
  indexes:
    synchronization:
      fixed-delay: 1 # Delay in minutes
    file-content-indexer:
      enabled: true # Enable fulltext search on file contents
