spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/duckcloud
    username: postgres
    password: postgres

  ## Keycloak SSO Authentication Server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/market
app:
  auth:
    allowed-origins: http://localhost:4200
  storage:
    endpoint: http://127.0.0.1:9000
    accessKey: SykAM0TXTf3OVp5j
    secretKey: JI4xH7DoE3q4GWlpomjiq3l6lkTn2xVS
  onlyoffice:
    jwt:
      secret: WlEJf7hdzCEGwTWkO89i
  server:
    public-base-url: "http://trodix.local:8010"