spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/duckcloud
    username: postgres
    password: postgres

  ## Keycloak SSO Authentication Server
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://trodix.local:8080/realms/market
      client:
        provider:
          market:
            token-uri: http://trodix.local:8080/realms/market/protocol/openid-connect/token
        registration:
          market:
            authorization-grant-type: client_credentials
            client-id: duckcloud-webservice
            client-secret: QOUUWPnujmoFwpiTduxjCD7yAhpdl8Jj

casbin:
  server:
    url: "http://localhost:7015"
    oauth2:
      client-id: "duckcloud-webservice"
      client-secret: "QOUUWPnujmoFwpiTduxjCD7yAhpdl8Jj"
      token-uri: "http://trodix.local:8080/realms/market/protocol/openid-connect/token"

app:
  elasticsearch-url: "localhost:9200"
  client:
    registration:
      name: market
      keycloak-admin-uri: http://trodix.local:8080/admin/realms/market
  auth:
    allowed-origins: http://localhost:4200
  storage:
    endpoint: http://127.0.0.1:9000
    accessKey: SykAM0TXTf3OVp5j
    secretKey: JI4xH7DoE3q4GWlpomjiq3l6lkTn2xVS

onlyoffice:
  jwt-secret: WlEJf7hdzCEGwTWkO89i
  app-server-base-url: "http://trodix.local:8010"
